<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <!-- FROM HERE.... -->
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <PublishReadyToRun>true</PublishReadyToRun>
        <PublishTrimmed>true</PublishTrimmed>
        <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
        <!-- TO HERE -->
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>fakeLanguage</PackageId>
        <Version>0.0.1</Version>
        <Authors>Dmitry Ponyatov</Authors>
        <Company>Horizon LLC</Company>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="lib/hello.fs" />
        <Compile Include="meta/cross.fs" />
        <Compile Include="meta/fileTreeLib.fs" />
        <Compile Include="meta/fileTree.fs" />
        <EmbeddedResource Include="lib/fake.ini" />
        <ProjectReference Include="compiler/compiler.fsproj" />
    </ItemGroup>

</Project>
